FROM node:16-alpine

USER node
 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install
# Since we are using docker-compose to sync this folder as a volume
# This COPY instruction below could be avoided. We are leaving it here to make this Dockerfile future and make it functional even without docker-compose
COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]
